Repository ISPC-TSDW/libroteka-backend, pull requests merged in 2025-05, with the labels that each got.

#14 Add images to books and edit permissions
  Libroteka/settings.py
  Libroteka/urls.py
  books/management/commands/__init__.py
  books/management/commands/init_groups.py
  books/migrations/0002_book_isbn_book_image_book_year_userslibroteka_role_and_more.py
  books/models.py
  books/serializer.py
  books/views.py
  initial_data.sql
  requirements.txt
Labels: Tarea, Back

#16 Modicacion serializer
  books/serializer.py
Labels: Back

#17 Modify initial data
  initial_data.sql
Labels: Back

#21 Se agregaron datos de prueba como usuarios, favoritos, ratings, statu…
  db.sql
  initial_data_test.sql
Labels: documentation, Back

#26 fix register and modify initial_data
  books/management/commands/init_groups.py
  books/views.py
  initial_data_test.sql
Labels: Back
